package pkg1stactivity;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class mikay extends javax.swing.JFrame {

 DefaultTableModel model;
    String ProductName;
    String Id;
    double Price = 0;
    double Total;
    int quantity;
    String SelectedItem;

    public mikay() {
        initComponents();
 model = (DefaultTableModel) Cart.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        NewDarkChocolate = new javax.swing.JLabel();
        NewCookies = new javax.swing.JLabel();
        NewButterscotch = new javax.swing.JLabel();
        NewVanilla = new javax.swing.JLabel();
        NewStrawberry = new javax.swing.JLabel();
        NewSaltedCaramel = new javax.swing.JLabel();
        NewDoubleDutch = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        P1 = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        P3 = new javax.swing.JLabel();
        P4 = new javax.swing.JLabel();
        P5 = new javax.swing.JLabel();
        P6 = new javax.swing.JLabel();
        P7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cart = new javax.swing.JTable();
        BB1 = new javax.swing.JButton();
        Quantity = new javax.swing.JTextField();
        items = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ravie", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("MIKAY'S ICE CREAM HOUSE");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 255), new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 255)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("ORDER CODE");

        B1.setText("1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setText("2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setText("3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B4.setText("4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setText("5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setText("6");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B7.setText("7");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(B1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B7)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 255), new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 255)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("FLAVORS");

        NewDarkChocolate.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        NewDarkChocolate.setText("DARK CHOCOLATE");

        NewCookies.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        NewCookies.setText("COOKIES & CREAM");

        NewButterscotch.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        NewButterscotch.setText("BUTTERSCOTCH");

        NewVanilla.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        NewVanilla.setText("VANILLA SWIRL");

        NewStrawberry.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        NewStrawberry.setText("STRAWBERRY DRIZZLE");

        NewSaltedCaramel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        NewSaltedCaramel.setText("SALTED CARAMEL");

        NewDoubleDutch.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        NewDoubleDutch.setText("DOUBLE DUTCH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewSaltedCaramel)
                    .addComponent(NewDoubleDutch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(NewStrawberry, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewDarkChocolate)
                            .addComponent(NewCookies)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NewButterscotch, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(NewVanilla)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(26, 26, 26))))))
                        .addGap(18, 18, 18))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addComponent(NewDarkChocolate)
                .addGap(18, 18, 18)
                .addComponent(NewCookies, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewButterscotch, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewVanilla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewStrawberry)
                .addGap(18, 18, 18)
                .addComponent(NewSaltedCaramel)
                .addGap(18, 18, 18)
                .addComponent(NewDoubleDutch)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 255), new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 255)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("PRICELIST");

        P1.setText("₱45.00");

        P2.setText("₱45.00");

        P3.setText("₱45.00");

        P4.setText("₱50.00");

        P5.setText("₱50.00");

        P6.setText("₱50.00");

        P7.setText("₱50.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(P1)
                .addGap(18, 18, 18)
                .addComponent(P2)
                .addGap(18, 18, 18)
                .addComponent(P3)
                .addGap(18, 18, 18)
                .addComponent(P4)
                .addGap(18, 18, 18)
                .addComponent(P5)
                .addGap(18, 18, 18)
                .addComponent(P6)
                .addGap(18, 18, 18)
                .addComponent(P7)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        Cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ORDER CODE", "FLAVOR", "PRICE", "QUANTITY", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(Cart);

        BB1.setText("ENTER");
        BB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BB1ActionPerformed(evt);
            }
        });

        Quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Quantity.setText("1");
        Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityActionPerformed(evt);
            }
        });

        items.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no add-ons", "sprinkles", "marshmallow" }));
        items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsActionPerformed(evt);
            }
        });

        jRadioButton1.setText("CARD");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("CASH");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 954, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BB1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22)
                                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(170, 170, 170)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(items, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRadioButton1)
                                        .addComponent(jRadioButton2))))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(4, 4, 4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BB1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(items, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jRadioButton2)))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
String selectedItem = items.getSelectedItem().toString();
    String quant = Quantity.getText();

    try {
        int validation = Integer.parseInt(quant);

        if (validation >= 1) {
            ProductName = B1.getText();

            if (selectedItem.equals("sprinkles")) {
                Id = "DARK CHOCOLATE + sprinkles";
            } else {
                Id = "DARK CHOCOLATE";
            }

            int itemPrice = 45; // Fixed price per unit
            quantity = validation;
            Total = itemPrice * quantity;

            model.addRow(new Object[]{ProductName, Id, itemPrice, quantity, Total});
            Quantity.setText("1");

        } else {
            JOptionPane.showMessageDialog(null, "Invalid Quantity!");
            Quantity.setText("1");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid number for quantity.");
        Quantity.setText("1");
    }
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
     String selectedItem = items.getSelectedItem().toString();
    String quant = Quantity.getText();

    try {
        int validation = Integer.parseInt(quant);

        if (validation >= 1) {
            ProductName = B2.getText();

            int basePrice;
            if (selectedItem.equals("sprinkles")) {
                Id = "COOKIES & CREAM + sprinkles";
                basePrice = 50;
            } else if (selectedItem.equals("")) {
                Id = "COOKIES & CREAM + marshmallow";
                basePrice = 45;
            } else {
                Id = "COOKIES & CREAM";
                basePrice = 40; // default price if no match
            }

            quantity = validation;
            Total = basePrice * quantity;

            model.addRow(new Object[]{ProductName, Id, basePrice, quantity, Total});
            Quantity.setText("1");
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Quantity!");
            Quantity.setText("1");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid number for quantity.");
        Quantity.setText("1");
    }
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
 String selectedItem = items.getSelectedItem().toString();
    String quant = Quantity.getText();

    try {
        int validation = Integer.parseInt(quant);

        if (validation >= 1) {
            ProductName = B3.getText();

            int basePrice;
            if (selectedItem.equals("sprinkles")) {
                Id = "BUTTERSCOTCH + sprinkles";
                basePrice = 45;
            } else if (selectedItem.equals("")) {
                Id = "BUTTERSCOTCH + marshmallow";
                basePrice = 45;
            } else {
                Id = "BUTTERSCOTCH";
                basePrice = 40; // default fallback price
            }

            quantity = validation;
            Total = basePrice * quantity;

            model.addRow(new Object[]{ProductName, Id, basePrice, quantity, Total});
            Quantity.setText("1");

        } else {
            JOptionPane.showMessageDialog(null, "Invalid Quantity!");
            Quantity.setText("1");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid number for quantity.");
        Quantity.setText("1");
    }
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        String selectedItem = items.getSelectedItem().toString();
    String quant = Quantity.getText();

    try {
        int validation = Integer.parseInt(quant);

        if (validation >= 1) {
            ProductName = B4.getText();

            int basePrice;
            if (selectedItem.equals("sprinkles")) {
                Id = "VANILLA SWIRL + sprinkles";
                basePrice = 50;
            } else if (selectedItem.equals("")) {
                Id = "VANILLA SWIRL + marshmallow";
                basePrice = 50;
            } else {
                Id = "VANILLA SWIRL";
                basePrice = 45; // fallback/default price
            }

            quantity = validation;
            Total = basePrice * quantity;

            model.addRow(new Object[]{ProductName, Id, basePrice, quantity, Total});
            Quantity.setText("1");

        } else {
            JOptionPane.showMessageDialog(null, "Invalid Quantity!");
            Quantity.setText("1");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid number for quantity.");
        Quantity.setText("1");
    }
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:

        SelectedItem = items.getSelectedItem().toString();
        String quant = Quantity.getText();
        int Validation = Integer.parseInt(quant);
        if (SelectedItem.equals("sprinkles")) {

            if (Validation >= 1) {
                ProductName = B5.getText();
                Id = "STRAWBERRY DRIZZLE + sprinkles";
                Price += 50;
                quantity = Integer.parseInt(Quantity.getText());
                Total = Price * quantity;

                model.addRow(new Object[]{ProductName, Id, Price, quantity});
                Quantity.setText("1");
            } else {
                JOptionPane.showMessageDialog(null, "Inavalid Quantity!");
                Quantity.setText("1");

            }
        } else if (SelectedItem.equals("")) {

            if (Validation >= 1) {
                ProductName = B5.getText();
                Id = "STRAWBERRY DRIZZLE + marshmallow";
                Price += 50;
                quantity = Integer.parseInt(Quantity.getText());
                Total = Price * quantity;

                model.addRow(new Object[]{ProductName, Id, Price, quantity, Total});
                Quantity.setText("1");
            } else {
                JOptionPane.showMessageDialog(null, "Inavalid Quantity!");
                Quantity.setText("1");

            }

        }
        
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        String selectedItem = items.getSelectedItem().toString();
    String quant = Quantity.getText();

    try {
        int validation = Integer.parseInt(quant);

        if (validation >= 1) {
            ProductName = B6.getText();
            int basePrice = Integer.parseInt(P6.getText());

            if (selectedItem.equals("sprinkles")) {
                Id = "SALTED CARAMEL + sprinkles";
            } else if (selectedItem.equals("")) {
                Id = "SALTED CARAMEL + marshmallow";
            } else {
                Id = "SALTED CARAMEL";
            }

            quantity = validation;
            Total = basePrice * quantity;

            model.addRow(new Object[]{ProductName, Id, basePrice, quantity, Total});
            Quantity.setText("1");

        } else {
            JOptionPane.showMessageDialog(null, "Invalid Quantity!");
            Quantity.setText("1");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid number for quantity.");
        Quantity.setText("1");
    }
        
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        SelectedItem = items.getSelectedItem().toString();
    String quant = Quantity.getText();
    int Validation = Integer.parseInt(quant);

    if (SelectedItem.equals("sprinkles")) {
        if (Validation >= 1) {
            ProductName = B7.getText();
            Id = "DOUBLE DUTCH + sprinkles";
            Price = 50; // Set the correct base price here
            quantity = Integer.parseInt(Quantity.getText());
            Total = Price * quantity;

            model.addRow(new Object[]{ProductName, Id, Price, quantity, Total});
            Quantity.setText("1");
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Quantity!");
            Quantity.setText("1");
        }
    } else if (SelectedItem.equals("")) {
        if (Validation >= 1) {
            ProductName = B7.getText();
            Id = "DOUBLE DUTCH + marshmallow";
            Price = 50; // Set the correct base price here
            quantity = Integer.parseInt(Quantity.getText());
            Total = Price * quantity;

            model.addRow(new Object[]{ProductName, Id, Price, quantity, Total});
            Quantity.setText("1");
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Quantity!");
            Quantity.setText("1");
        }
    }
    }//GEN-LAST:event_B7ActionPerformed

    private void BB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BB1ActionPerformed
     double grandTotal = 0.0;

    
    for (int i = 0; i < model.getRowCount(); i++) {
        Object totalObj = model.getValueAt(i, 4); 
        if (totalObj != null) {
            try {
                double rowTotal = Double.parseDouble(totalObj.toString());
                grandTotal += rowTotal;
            } catch (NumberFormatException e) {
                
                System.out.println("Invalid total value at row " + i);
            }
        }
    }

    
    JOptionPane.showMessageDialog(null, "Total Amount: ₱" + grandTotal);
    }//GEN-LAST:event_BB1ActionPerformed

    private void QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityActionPerformed

    private void itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemsActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mikay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mikay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mikay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mikay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mikay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton BB1;
    private javax.swing.JTable Cart;
    private javax.swing.JLabel NewButterscotch;
    private javax.swing.JLabel NewCookies;
    private javax.swing.JLabel NewDarkChocolate;
    private javax.swing.JLabel NewDoubleDutch;
    private javax.swing.JLabel NewSaltedCaramel;
    private javax.swing.JLabel NewStrawberry;
    private javax.swing.JLabel NewVanilla;
    private javax.swing.JLabel P1;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel P3;
    private javax.swing.JLabel P4;
    private javax.swing.JLabel P5;
    private javax.swing.JLabel P6;
    private javax.swing.JLabel P7;
    private javax.swing.JTextField Quantity;
    private javax.swing.JComboBox<String> items;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
